# Generated by Django 2.0.7 on 2018-07-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptodo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoapp',
            name='time_added',
            field=models.DateTimeField(),
        ),
    ]
