# Generated by Django 2.0.7 on 2018-08-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptodo', '0002_auto_20180731_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoapp',
            name='due_date',
            field=models.DateTimeField(default='2018-08-07'),
        ),
        migrations.AlterField(
            model_name='todoapp',
            name='time_added',
            field=models.DateTimeField(default='2018-08-07'),
        ),
    ]
