# Generated by Django 2.0.7 on 2018-10-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptodo', '0008_auto_20180906_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoapp',
            name='title',
        ),
        migrations.AddField(
            model_name='todoapp',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='todoapp',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='todoapp',
            name='due_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='todoapp',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='todoapp',
            name='time_added',
            field=models.DateTimeField(default='2018-10-02'),
        ),
    ]
