# Generated by Django 2.0.7 on 2018-10-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptodo', '0009_auto_20181002_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Location',
            field=models.CharField(default='my Location default', max_length=100),
        ),
        migrations.AlterField(
            model_name='todoapp',
            name='time_added',
            field=models.DateTimeField(default='2018-10-03'),
        ),
    ]
