# Generated by Django 2.0.7 on 2018-10-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptodo', '0010_auto_20181003_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoapp',
            name='time_added',
            field=models.DateTimeField(default='2018-10-05'),
        ),
    ]
