# Generated by Django 2.0.7 on 2018-10-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptodo', '0011_auto_20181005_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoapp',
            name='time_added',
            field=models.DateTimeField(default='2018-10-06'),
        ),
    ]
